### ISSUE TITLE
Wire up to HAX w/ more properties

### ISSUE THREAD

**Issue by btopro** [LRNWebComponents/stop-note#1]
Stop sign -Let's make this an SVG based icon
turn the stop sign into an iron-icon then use the paper-icon-picker element (in hax as iconpicker) to allow for people to pick between a few icons so that this ins't just stop by it's a hand, it's stop sign, it's a warning or a notice and then based on those things we could change the color dynamically. So stop sign is red by a thumbs up is green but a warning sign is yellow sorta deal.

Then you'd have a more repurposable note related to calling attention to something else some place. Adding a link as an option for the "go read..." would also allow for linking internal to content

**Comment by cgldevel** [comment]
Sounds good... I was making this quickly for Louis (Chem) so that he could see an example, I could get additional feedback from him, etc.  All solid suggestions though, I will keep working on it!
